scrape_configs:
- job_name: myapp
  scrape_interval: 5s
  static_configs:
  - targets:
    - host.docker.internal:9004
  metrics_path: /metrics

- job_name: dummy_non_scrappable_target
  scrape_interval: 5s
  static_configs:
    - targets:
        - host.docker.internal:9091
  honor_labels: true

